#!/bin/sh

#1.查看进程编号
ps -ef |grep fsiAlgFoam

#2.杀死进程
kill -9 进程编号 

#3.for循环($1 表示第一个输入的参数，$2表示第二个输入的参数)
for i in $(seq 1 1 $1)
do
  #You code 
done

#4.查找所有文件名为controlDict中带true的行
find -name controlDict | xargs grep "true"

#5.删除文件名为带小数点后三位的文件
ls |grep ^[0-9].[0-9][0-9][0-9] | xargs rm -rf

